OpenStack:

    host: http://:5000/v2.0
    user: admin
    passwd: 
    tenantName: 
rabbitMQ:
    host: localhost
    user: 
    passwd: 
QueueSettings:
    retryCount: 10
    ProjectQueueName: Project_Queue
    UserQueueName: User_Queue
    VMQueueName: VM_Queue
    UpgradeQueueName: Upgrade_Queue
    ResizeQueueName: Resize_Queue
    MuranoQueueName: Murano_Queue
    AddonQueueName: Addon_Queue
    UnSubscribeQueueName: UnSubscribe_Queue
UserSettings:
    DefaultUserPassword: 
